export const shrdg = deepCamelcaseKeys({
	id: '6b91763f17e44f53b14219b45e85d1cb3e8ed7fc',
	parent_id: 'a6c3c604f83748a3a372ffdd08c6a76780681753',
	user_id: '7edc03c7ab5d4205a78b6906b841eebf2f11b38f',
	document_name: 'sn-blog',
	page_count: '1',
	created: '1700069898',
	updated: '1700069949',
	original_filename: 'sn-blog.jpg',
	origin_document_id: null,
	owner: 'viktoriia.derkach+modal+sms@airslate.com',
	owner_name: 'Vika modal',
	template: false,
	origin_user_id: null,
	version_time: '1700069949',
	thumbnail: {
		small:
			'https://app3.signnow-dev.xyz/api/document/6b91763f17e44f53b14219b45e85d1cb3e8ed7fc/thumbnail?size=small',
		medium:
			'https://app3.signnow-dev.xyz/api/document/6b91763f17e44f53b14219b45e85d1cb3e8ed7fc/thumbnail?size=medium',
		large:
			'https://app3.signnow-dev.xyz/api/document/6b91763f17e44f53b14219b45e85d1cb3e8ed7fc/thumbnail?size=large',
	},
	roles: [],
	viewer_roles: [
		{
			unique_id: '64c067ccc0c746af989c25b1c423cce73a41b52a',
			signing_order: '1',
			name: 'Viewer 1',
		},
		{
			unique_id: '3021e2cc7cdd456e917e4d7f801bb6056e8dbad5',
			signing_order: '2',
			name: 'Viewer 3',
		},
		{
			unique_id: '5cf85e096f53431eae229f3aeb1cb577c17448ef',
			signing_order: '3',
			name: 'Viewer 5',
		},
	],
	attachments: [],
	checks: [],
	document_group_info: {
		document_group_id: '74daddb9f0d247d989fc9394f6f14ef3566a6b55',
		document_group_name: 'Document Group 15-11-2023',
		invite_id: '1d3c173996044bbf9f8e5f85a12a34153afe5b42',
		invite_status: 'pending',
		sign_as_merged: true,
		doc_count_in_group: 3,
		freeform_invite: {
			id: null,
		},
		state: 'pending',
	},
	document_group_template_info: [],
	integrations: [],
	settings: {
		no_document_attachment: false,
		copy_export: false,
		no_user_signature_return: false,
		mobileweb_option: false,
		require_drawn_signatures: false,
		org_allowed_team_admins: false,
		cloud_auto_export: false,
		digitally_sign_dowloaded_docs: false,
		flatten_document_fields: false,
		invite_completion_redirect_url: false,
		invite_decline_redirect_url: false,
		add_signature_stamp: false,
		pending_invite_document_view_notification: false,
		required_preset_signature_name: false,
		signing_link_document_download: false,
		cloud_export_with_history: false,
		emailed_docs_include_history: false,
		document_completion_retention_days: false,
		require_email_subject: false,
		require_login_for_signing: false,
		logout_on_signing: false,
		audit_trail_completion_retention_days: false,
		front_end_session_length: false,
		email_admin_on_banned_login: false,
		add_signature_stamp_with_name: false,
		cfr_title_21_part_11: false,
		unsuccessful_logout_attempts_allowed: false,
		no_document_file_attachments: false,
		enable_hyperlink_protection: false,
		enable_advanced_threat_protection: false,
		require_authentication_for_invites: false,
		electronic_consent_required: false,
		electronic_consent_text: false,
		document_guide: false,
		restrict_download: false,
		watermark_downloaded_document: false,
		disable_email_notifications: false,
		upload_limit: false,
		document_schema_extended: false,
		invite_update_notifications_for_all_invites_at_invite_create: false,
		enable_full_story_tracker: false,
		document_attachment_only_for_signer: false,
		enable_experiments: false,
		block_export_options_when_credit_card_validation_is_used: false,
		'sso-only-login': false,
		only_administrator_is_able_to_invite_to_the_team: false,
		block_login_via_social_networks: false,
		redirect_to_registration_when_fields_saved: false,
		common_experiments: false,
		hide_decline_to_sign_option_in_signing_session: false,
		hide_upgrade_subscription_button: false,
		mytext: false,
		mytext1: false,
		ololo: false,
		allow_download_certificate: false,
		enable_eu_date_format: false,
		guide_signers_only_through_required_fields: false,
		allow_document_copying_to_other_accounts: false,
		email_custom_subject: false,
		email_custom_message: false,
		enable_mfa: false,
		max_attachments_for_signnow_fields_per_document: false,
		allow_big_attachment_file: false,
		allow_big_count_of_attachment_fields_per_document: false,
		enable_qwer: false,
		disable_download_action_in_editor: false,
		signature_stamp_position: false,
		enable_pki: false,
		enable_document_comments: false,
		auto_deletion_documents_from_trash: false,
		save_signer_signature_and_initials: false,
		auto_apply_signatures_and_initials_to_document_fields: false,
		block_organization_selfleave_by_member: false,
		agreement_to_test_new_functionality_in_organization: false,
		agree_to_be_beta_tester: false,
		completed_document_name_formula: false,
		default_field_invite_remind_before: false,
		default_field_invite_remind_after: false,
		default_field_invite_remind_repeat: false,
		default_field_invite_expiration_time: false,
		email_logo_position: false,
		email_btn_bkgd_color: false,
		email_btn_text_color: false,
		allow_edit_document_after_signing: false,
		allow_embedded_extended_token_expiration: false,
		email_footer_enabled: false,
		every_signature_and_initials_field_requires_user_authentication: false,
		enable_team_admin_move_docs: false,
		disable_recipients_list_from_editor: false,
		allow_team_admin_rename_docs: false,
		disable_email_recipients: false,
		parse_only_signature_fields: false,
		flatten_before_aspose: false,
		run_experiments: false,
		disable_form_search: false,
		allow_team_admin_create_csv_report_for_shared_template: false,
		enable_team_generic_email: false,
		use_team_generic_data: false,
		allow_qes: false,
		enable_qes: false,
		advanced_signing_flow: false,
	},
	signing_session_settings: {
		welcome_message: null,
	},
	tags: [],
	enumeration_options: [],
	exported_to: [],
	fields: [],
	field_invites: [],
	viewer_field_invites: [
		{
			id: '261c8323ccd6461a9c96fd3d98bc8df98652256e',
			signer_user_id: '4f6129002e2a4a85b0f58dc0c8d76798fc078272',
			status: 'fulfilled',
			created: '1700069949',
			role: 'Viewer 1',
			updated: '1700069949',
			email: 'radchenko.illia@airslate.com',
			role_id: '64c067ccc0c746af989c25b1c423cce73a41b52a',
			email_group: {
				id: null,
				name: null,
			},
			email_statuses: [],
		},
		{
			id: '4f9bb7a5db874fb09a35eacd47464fa3a80cf293',
			signer_user_id: '7edc03c7ab5d4205a78b6906b841eebf2f11b38f',
			status: 'created',
			created: '1700069949',
			role: 'Viewer 3',
			updated: '1700069949',
			email: 'viktoriia.derkach+modal+sms@airslate.com',
			role_id: '3021e2cc7cdd456e917e4d7f801bb6056e8dbad5',
			email_group: {
				id: null,
				name: null,
			},
			email_statuses: [],
		},
		{
			id: '628739bc24a842c698b3339d57850ff20c261a38',
			signer_user_id: '267fe0cc0a8f4546b61382944d6701f0a8324fcb',
			status: 'created',
			created: '1700069949',
			role: 'Viewer 5',
			updated: '1700069949',
			email: 'ff@fmail.com',
			role_id: '5cf85e096f53431eae229f3aeb1cb577c17448ef',
			email_group: {
				id: null,
				name: null,
			},
			email_statuses: [],
		},
	],
	field_validators: [],
	hyperlinks: [],
	inserts: [],
	notary_invites: [],
	originator_organization_settings: [],
	payments: [],
	radiobuttons: [],
	seals: [],
	signatures: [],
	requests: [],
	routing_details: [
		{
			id: 'f68df12707e54eee83fdbe9f89af7059ef1d56f4',
			data: [],
			created: '1700069934',
			updated: '1700069934',
			cc: [],
			cc_step: [],
			invite_link_instructions: null,
			viewers: [
				{
					default_email: 'radchenko.illia@airslate.com',
					name: 'radchenko.illia@airslate.com',
					signing_order: 1,
					inviter_role: false,
				},
				{
					default_email: 'viktoriia.derkach+modal+sms@airslate.com',
					name: 'viktoriia.derkach+modal+sms@airslate.com',
					signing_order: 1,
					inviter_role: false,
				},
				{
					default_email: 'ff@fmail.com',
					name: 'ff@fmail.com',
					signing_order: 1,
					inviter_role: false,
				},
			],
		},
	],
	texts: [],
	originator_logo: '',
	pages: [
		{
			src: 'https://app3.signnow-dev.xyz/api/document/6b91763f17e44f53b14219b45e85d1cb3e8ed7fc/thumbnail?size=large&page=0',
			size: {
				width: 591,
				height: 1280,
			},
		},
	],
	lines: [],
});

export const arrDg = deepCamelcaseKeys([
	{
		created: 1699903922,
		id: '73af7f64422f4be0b2db43852869e68b940f1cda',
		user_id: '7edc03c7ab5d4205a78b6906b841eebf2f11b38f',
		document_name: 'Screenshot 2023-11-13 at 21.11.24',
		document_group_info: {
			document_group_id: '549b7f74aa2c4593899a951c2c32070793a0b7fa',
			document_group_name: 'Document Group 13-11-2023',
			invite_id: '3ffdfc2833974e9a872544f3df573aab492e1f4e',
			invite_status: 'pending',
			doc_count_in_group: 2,
			sign_as_merged: true,
			freeform_invite: {
				id: null,
			},
			state: 'pending',
		},
		updated: 1699903965,
		owner: 'viktoriia.derkach+modal+sms@airslate.com',
		thumbnail: {
			small:
				'https://app3.signnow-dev.xyz/api/document/73af7f64422f4be0b2db43852869e68b940f1cda/thumbnail?size=small',
			medium:
				'https://app3.signnow-dev.xyz/api/document/73af7f64422f4be0b2db43852869e68b940f1cda/thumbnail?size=medium',
			large:
				'https://app3.signnow-dev.xyz/api/document/73af7f64422f4be0b2db43852869e68b940f1cda/thumbnail?size=large',
		},
		viewer_roles: [
			{
				unique_id: '4f5ccfd9208f46b3b4ddb92fff0afbfbac384535',
				signing_order: '1',
				name: 'Viewer 1',
			},
		],
		viewer_field_invites: [
			{
				id: '6041bc2c235a48619fe0adfbff4c342ceae022e3',
				signer_user_id: '907222e38a7a44c18cec1c6385f4a486a420c2f3',
				status: 'fulfilled',
				created: '1699903966',
				role: 'Viewer 1',
				updated: '1699903966',
				email: 'viktoriia.derkach@airslate.com',
				role_id: '4f5ccfd9208f46b3b4ddb92fff0afbfbac384535',
				email_sent_statuses: [],
				email_group: {
					id: null,
					name: null,
				},
			},
		],
		requests: [],
		has_fields: false,
		has_conditional_fields: false,
		has_conditional_routing: false,
		page_count: '1',
		waiting_for: [],
		roles: [],
		routing_details: [
			{
				id: '96ba30a69592478c89480ec054f72d037d502303',
				data: [],
				created: '1699903953',
				updated: '1699903953',
				cc: [],
				cc_step: [],
				invite_link_instructions: null,
				viewers: [
					{
						default_email: 'viktoriia.derkach@airslate.com',
						name: 'viktoriia.derkach@airslate.com',
						signing_order: 1,
						inviter_role: false,
					},
				],
			},
		],
		field_invites: [],
		attachments: [],
		tags: [],
		template: false,
		signatures: [],
		document_group_template_info: [],
		needs_more_fulfillment: false,
		original_owner: true,
		settings: {
			no_document_attachment: false,
			copy_export: false,
			no_user_signature_return: false,
			mobileweb_option: false,
			require_drawn_signatures: false,
			org_allowed_team_admins: false,
			cloud_auto_export: false,
			digitally_sign_dowloaded_docs: false,
			flatten_document_fields: false,
			invite_completion_redirect_url: false,
			invite_decline_redirect_url: false,
			add_signature_stamp: false,
			pending_invite_document_view_notification: false,
			required_preset_signature_name: false,
			signing_link_document_download: false,
			cloud_export_with_history: false,
			emailed_docs_include_history: false,
			document_completion_retention_days: false,
			require_email_subject: false,
			require_login_for_signing: false,
			logout_on_signing: false,
			audit_trail_completion_retention_days: false,
			front_end_session_length: false,
			email_admin_on_banned_login: false,
			add_signature_stamp_with_name: false,
			cfr_title_21_part_11: false,
			unsuccessful_logout_attempts_allowed: false,
			no_document_file_attachments: false,
			enable_hyperlink_protection: false,
			enable_advanced_threat_protection: false,
			require_authentication_for_invites: false,
			electronic_consent_required: false,
			electronic_consent_text: false,
			document_guide: false,
			restrict_download: false,
			watermark_downloaded_document: false,
			disable_email_notifications: false,
			upload_limit: false,
			document_schema_extended: false,
			invite_update_notifications_for_all_invites_at_invite_create: false,
			enable_full_story_tracker: false,
			document_attachment_only_for_signer: false,
			enable_experiments: false,
			block_export_options_when_credit_card_validation_is_used: false,
			'sso-only-login': false,
			only_administrator_is_able_to_invite_to_the_team: false,
			block_login_via_social_networks: false,
			redirect_to_registration_when_fields_saved: false,
			common_experiments: false,
			hide_decline_to_sign_option_in_signing_session: false,
			hide_upgrade_subscription_button: false,
			mytext: false,
			mytext1: false,
			ololo: false,
			do_no_consent_redirect_url: false,
			lock_signing_date_by_default: false,
			allow_download_certificate: false,
			have_merged_document_group_option: false,
			enable_eu_date_format: false,
			guide_signers_only_through_required_fields: false,
			allow_document_copying_to_other_accounts: false,
			email_custom_subject: false,
			email_custom_message: false,
			invite_expiration_days: false,
			enable_mfa: false,
			enable_document_download_link_for_invite_completion_mails: false,
			max_attachments_for_signnow_fields_per_document: false,
			allow_big_attachment_file: false,
			allow_big_count_of_attachment_fields_per_document: false,
			enable_hyperlink_field: false,
			enable_qwer: false,
			disable_download_action_in_editor: false,
			signature_stamp_position: false,
			enable_pki: false,
			enable_document_comments: false,
			auto_deletion_documents_from_trash: false,
			cc_completion_email_contain_only_downloading_document_link: false,
			save_signer_signature_and_initials: false,
			auto_apply_signatures_and_initials_to_document_fields: false,
			block_organization_selfleave_by_member: false,
			receive_signer_email_after_sent_field_invite_to_yourself: false,
			agreement_to_test_new_functionality_in_organization: false,
			agree_to_be_beta_tester: false,
			completed_document_name_formula: false,
			date_format: false,
			default_field_invite_remind_before: false,
			default_field_invite_remind_after: false,
			default_field_invite_remind_repeat: false,
			default_field_invite_expiration_time: false,
			email_logo_position: false,
			email_btn_bkgd_color: false,
			email_btn_text_color: false,
			allow_edit_document_after_signing: false,
			allow_embedded_extended_token_expiration: false,
			email_footer_enabled: false,
			every_signature_and_initials_field_requires_user_authentication: false,
			enable_render_pages_in_editor_as_images: false,
			enable_team_admin_move_docs: false,
			disable_recipients_list_from_editor: false,
			allow_team_admin_rename_docs: false,
			disable_email_recipients: false,
			parse_only_signature_fields: false,
			flatten_before_aspose: false,
			run_experiments: false,
			disable_form_search: false,
			allow_team_admin_create_csv_report_for_shared_template: false,
			enable_team_generic_email: false,
			use_team_generic_data: false,
			signing_reason: false,
			allow_qes: false,
			enable_qes: false,
			advanced_signing_flow: false,
		},
		is_favorite: false,
		entity_type: 'document',
		origin_document_id: null,
		recently_used: '1699903965',
	},
	{
		created: 1699903914,
		id: 'f56f20e260d7413d9998f9915f244b6efc15d128',
		user_id: '7edc03c7ab5d4205a78b6906b841eebf2f11b38f',
		document_name: 'Screenshot 2023-11-09 at 12.07.58',
		document_group_info: {
			document_group_id: '549b7f74aa2c4593899a951c2c32070793a0b7fa',
			document_group_name: 'Document Group 13-11-2023',
			invite_id: '3ffdfc2833974e9a872544f3df573aab492e1f4e',
			invite_status: 'pending',
			doc_count_in_group: 2,
			sign_as_merged: true,
			freeform_invite: {
				id: null,
			},
			state: 'pending',
		},
		updated: 1699903965,
		owner: 'viktoriia.derkach+modal+sms@airslate.com',
		thumbnail: {
			small:
				'https://app3.signnow-dev.xyz/api/document/f56f20e260d7413d9998f9915f244b6efc15d128/thumbnail?size=small',
			medium:
				'https://app3.signnow-dev.xyz/api/document/f56f20e260d7413d9998f9915f244b6efc15d128/thumbnail?size=medium',
			large:
				'https://app3.signnow-dev.xyz/api/document/f56f20e260d7413d9998f9915f244b6efc15d128/thumbnail?size=large',
		},
		viewer_roles: [],
		viewer_field_invites: [],
		requests: [],
		has_fields: true,
		has_conditional_fields: false,
		has_conditional_routing: false,
		page_count: '1',
		waiting_for: ['viktoriia.derkach@airslate.com'],
		roles: [
			{
				unique_id: 'b8c4c34f46304d3688d2d2999c32c218ca63ca2e',
				signing_order: '1',
				name: 'viktoriia.derkach@airslate.com',
			},
		],
		routing_details: [
			{
				id: '0ce0bd7bc8d54b71a1ed99b59c9a8b0451b971fb',
				data: [
					{
						default_email: 'viktoriia.derkach@airslate.com',
						inviter_role: false,
						decline_by_signature: false,
						role_id: 'b8c4c34f46304d3688d2d2999c32c218ca63ca2e',
						name: 'viktoriia.derkach@airslate.com',
						signing_order: 1,
					},
				],
				created: '1699903953',
				updated: '1699903953',
				cc: [],
				cc_step: [],
				invite_link_instructions: null,
				viewers: [],
			},
		],
		field_invites: [
			{
				id: '72820813d39a40468d34183120316275048117b0',
				signer_user_id: '907222e38a7a44c18cec1c6385f4a486a420c2f3',
				status: 'pending',
				email_sent_statuses: [],
				is_document_locked: '0',
				password_protected: false,
				password_type: '',
				password_method: '',
				reassign: false,
				id_verification_required: 'NO',
				id_verified: 'UNVERIFIED',
				created: '1699903966',
				email: 'viktoriia.derkach@airslate.com',
				role: 'viktoriia.derkach@airslate.com',
				reminder: '0',
				updated: '1699903966',
				expiration_time: '1702495966',
				role_id: 'b8c4c34f46304d3688d2d2999c32c218ca63ca2e',
				electronic_consent_id: null,
				declined: [],
				prefill_signature_name: null,
				force_new_signature: null,
				signing_instructions: null,
				required_preset_signature_name: null,
				decline_by_signature: '0',
				electronic_consent_required: 0,
				payment_request: null,
				is_draft_exists: '0',
				is_full_declined: false,
				is_embedded: false,
				delivery_type: 'email',
				signer_phone_invite: null,
				email_group: {
					id: null,
					name: null,
				},
				signature_type: null,
				unique_id: 'b8c4c34f46304d3688d2d2999c32c218ca63ca2e',
				signing_order: '1',
				name: 'viktoriia.derkach@airslate.com',
				request_id: 'fadfffb5540c40eea8227c19a5004882c6268810',
				signing_status: 'email-sent',
			},
		],
		attachments: [],
		tags: [
			{
				type: 'system',
				name: 'field_signature',
			},
			{
				type: 'system',
				name: 'fields',
			},
		],
		template: false,
		signatures: [],
		document_group_template_info: [],
		needs_more_fulfillment: false,
		original_owner: true,
		settings: {
			no_document_attachment: false,
			copy_export: false,
			no_user_signature_return: false,
			mobileweb_option: false,
			require_drawn_signatures: false,
			org_allowed_team_admins: false,
			cloud_auto_export: false,
			digitally_sign_dowloaded_docs: false,
			flatten_document_fields: false,
			invite_completion_redirect_url: false,
			invite_decline_redirect_url: false,
			add_signature_stamp: false,
			pending_invite_document_view_notification: false,
			required_preset_signature_name: false,
			signing_link_document_download: false,
			cloud_export_with_history: false,
			emailed_docs_include_history: false,
			document_completion_retention_days: false,
			require_email_subject: false,
			require_login_for_signing: false,
			logout_on_signing: false,
			audit_trail_completion_retention_days: false,
			front_end_session_length: false,
			email_admin_on_banned_login: false,
			add_signature_stamp_with_name: false,
			cfr_title_21_part_11: false,
			unsuccessful_logout_attempts_allowed: false,
			no_document_file_attachments: false,
			enable_hyperlink_protection: false,
			enable_advanced_threat_protection: false,
			require_authentication_for_invites: false,
			electronic_consent_required: false,
			electronic_consent_text: false,
			document_guide: false,
			restrict_download: false,
			watermark_downloaded_document: false,
			disable_email_notifications: false,
			upload_limit: false,
			document_schema_extended: false,
			invite_update_notifications_for_all_invites_at_invite_create: false,
			enable_full_story_tracker: false,
			document_attachment_only_for_signer: false,
			enable_experiments: false,
			block_export_options_when_credit_card_validation_is_used: false,
			'sso-only-login': false,
			only_administrator_is_able_to_invite_to_the_team: false,
			block_login_via_social_networks: false,
			redirect_to_registration_when_fields_saved: false,
			common_experiments: false,
			hide_decline_to_sign_option_in_signing_session: false,
			hide_upgrade_subscription_button: false,
			mytext: false,
			mytext1: false,
			ololo: false,
			do_no_consent_redirect_url: false,
			lock_signing_date_by_default: false,
			allow_download_certificate: false,
			have_merged_document_group_option: false,
			enable_eu_date_format: false,
			guide_signers_only_through_required_fields: false,
			allow_document_copying_to_other_accounts: false,
			email_custom_subject: false,
			email_custom_message: false,
			invite_expiration_days: false,
			enable_mfa: false,
			enable_document_download_link_for_invite_completion_mails: false,
			max_attachments_for_signnow_fields_per_document: false,
			allow_big_attachment_file: false,
			allow_big_count_of_attachment_fields_per_document: false,
			enable_hyperlink_field: false,
			enable_qwer: false,
			disable_download_action_in_editor: false,
			signature_stamp_position: false,
			enable_pki: false,
			enable_document_comments: false,
			auto_deletion_documents_from_trash: false,
			cc_completion_email_contain_only_downloading_document_link: false,
			save_signer_signature_and_initials: false,
			auto_apply_signatures_and_initials_to_document_fields: false,
			block_organization_selfleave_by_member: false,
			receive_signer_email_after_sent_field_invite_to_yourself: false,
			agreement_to_test_new_functionality_in_organization: false,
			agree_to_be_beta_tester: false,
			completed_document_name_formula: false,
			date_format: false,
			default_field_invite_remind_before: false,
			default_field_invite_remind_after: false,
			default_field_invite_remind_repeat: false,
			default_field_invite_expiration_time: false,
			email_logo_position: false,
			email_btn_bkgd_color: false,
			email_btn_text_color: false,
			allow_edit_document_after_signing: false,
			allow_embedded_extended_token_expiration: false,
			email_footer_enabled: false,
			every_signature_and_initials_field_requires_user_authentication: false,
			enable_render_pages_in_editor_as_images: false,
			enable_team_admin_move_docs: false,
			disable_recipients_list_from_editor: false,
			allow_team_admin_rename_docs: false,
			disable_email_recipients: false,
			parse_only_signature_fields: false,
			flatten_before_aspose: false,
			run_experiments: false,
			disable_form_search: false,
			allow_team_admin_create_csv_report_for_shared_template: false,
			enable_team_generic_email: false,
			use_team_generic_data: false,
			signing_reason: false,
			allow_qes: false,
			enable_qes: false,
			advanced_signing_flow: false,
		},
		is_favorite: false,
		entity_type: 'document',
		origin_document_id: null,
		recently_used: '1699903965',
		has_pending_payment_request: false,
		has_processing_payment_request: false,
	},
]);

export const dg = deepCamelcaseKeys({
	created: 1699976213,
	id: '94cc6f41b1c44d8492a90979f10954f4cf7d52c4',
	user_id: '4f6129002e2a4a85b0f58dc0c8d76798fc078272',
	document_name: '1620769146_15-phonoteka_org-p-fon-dlya-zum-stena-25',
	document_group_info: {
		document_group_id: '0e42b8a166364e22899fb28cde2550b4209adf98',
		document_group_name: 'Document Group 14-11-2023',
		invite_id: '38c65be07afd47a7b7842d07f69810f73c1fa3e5',
		invite_status: 'pending',
		doc_count_in_group: 2,
		sign_as_merged: true,
		freeform_invite: {
			id: null,
		},
		state: 'pending',
	},
	updated: 1699976268,
	owner: 'radchenko.illia@airslate.com',
	thumbnail: {
		small:
			'https://app3.signnow-dev.xyz/api/document/94cc6f41b1c44d8492a90979f10954f4cf7d52c4/thumbnail?size=small',
		medium:
			'https://app3.signnow-dev.xyz/api/document/94cc6f41b1c44d8492a90979f10954f4cf7d52c4/thumbnail?size=medium',
		large:
			'https://app3.signnow-dev.xyz/api/document/94cc6f41b1c44d8492a90979f10954f4cf7d52c4/thumbnail?size=large',
	},
	viewer_roles: [
		{
			unique_id: '175d172148964c18aa5fd5e59f1fdf6a903ef884',
			signing_order: '1',
			name: 'Viewer 1',
		},
	],
	viewer_field_invites: [
		{
			id: '75cffbfa4ce1406dbbc68b481e26be44b50439cd',
			signer_user_id: '907222e38a7a44c18cec1c6385f4a486a420c2f3',
			status: 'fulfilled',
			created: '1699976268',
			role: 'Viewer 1',
			updated: '1699976268',
			email: 'viktoriia.derkach@airslate.com',
			role_id: '175d172148964c18aa5fd5e59f1fdf6a903ef884',
			email_sent_statuses: [],
			email_group: {
				id: null,
				name: null,
			},
		},
	],
	requests: [],
	has_fields: false,
	has_conditional_fields: false,
	has_conditional_routing: false,
	page_count: '1',
	waiting_for: [],
	roles: [],
	routing_details: [
		{
			id: 'dbc75c02a5624058be222ac79ecc71b6fdf9edb1',
			data: [],
			created: '1699976221',
			updated: '1699976240',
			cc: [],
			cc_step: [],
			invite_link_instructions: null,
			viewers: [
				{
					default_email: 'viktoriia.derkach@airslate.com',
					name: 'Recipient 1',
					signing_order: 1,
					inviter_role: false,
				},
			],
		},
	],
	field_invites: [],
	attachments: [],
	tags: [],
	template: false,
	signatures: [],
	document_group_template_info: [],
	needs_more_fulfillment: false,
	original_owner: true,
	settings: {
		no_document_attachment: true,
		copy_export: false,
		no_user_signature_return: false,
		mobileweb_option: false,
		require_drawn_signatures: false,
		org_allowed_team_admins: false,
		cloud_auto_export: false,
		digitally_sign_dowloaded_docs: false,
		flatten_document_fields: false,
		invite_completion_redirect_url: false,
		invite_decline_redirect_url: false,
		add_signature_stamp: false,
		pending_invite_document_view_notification: false,
		required_preset_signature_name: false,
		signing_link_document_download: false,
		cloud_export_with_history: false,
		emailed_docs_include_history: false,
		document_completion_retention_days: false,
		require_email_subject: false,
		require_login_for_signing: false,
		logout_on_signing: false,
		audit_trail_completion_retention_days: false,
		front_end_session_length: false,
		email_admin_on_banned_login: false,
		add_signature_stamp_with_name: false,
		cfr_title_21_part_11: false,
		unsuccessful_logout_attempts_allowed: false,
		no_document_file_attachments: false,
		enable_hyperlink_protection: false,
		enable_advanced_threat_protection: false,
		require_authentication_for_invites: false,
		electronic_consent_required: false,
		electronic_consent_text: false,
		document_guide: false,
		restrict_download: false,
		watermark_downloaded_document: false,
		disable_email_notifications: false,
		upload_limit: false,
		document_schema_extended: false,
		invite_update_notifications_for_all_invites_at_invite_create: false,
		enable_full_story_tracker: false,
		document_attachment_only_for_signer: false,
		enable_experiments: false,
		block_export_options_when_credit_card_validation_is_used: false,
		'sso-only-login': false,
		only_administrator_is_able_to_invite_to_the_team: false,
		block_login_via_social_networks: false,
		redirect_to_registration_when_fields_saved: false,
		common_experiments: false,
		hide_decline_to_sign_option_in_signing_session: false,
		hide_upgrade_subscription_button: false,
		mytext: false,
		mytext1: false,
		ololo: false,
		do_no_consent_redirect_url: false,
		lock_signing_date_by_default: false,
		allow_download_certificate: false,
		have_merged_document_group_option: false,
		enable_eu_date_format: false,
		guide_signers_only_through_required_fields: false,
		allow_document_copying_to_other_accounts: false,
		email_custom_subject: false,
		email_custom_message: false,
		invite_expiration_days: false,
		enable_mfa: false,
		enable_document_download_link_for_invite_completion_mails: false,
		max_attachments_for_signnow_fields_per_document: false,
		allow_big_attachment_file: false,
		allow_big_count_of_attachment_fields_per_document: false,
		enable_hyperlink_field: false,
		enable_qwer: false,
		disable_download_action_in_editor: false,
		signature_stamp_position: false,
		enable_pki: false,
		enable_document_comments: false,
		auto_deletion_documents_from_trash: false,
		cc_completion_email_contain_only_downloading_document_link: false,
		save_signer_signature_and_initials: false,
		auto_apply_signatures_and_initials_to_document_fields: false,
		block_organization_selfleave_by_member: false,
		receive_signer_email_after_sent_field_invite_to_yourself: false,
		agreement_to_test_new_functionality_in_organization: false,
		agree_to_be_beta_tester: false,
		completed_document_name_formula: false,
		date_format: false,
		default_field_invite_remind_before: false,
		default_field_invite_remind_after: false,
		default_field_invite_remind_repeat: false,
		default_field_invite_expiration_time: false,
		email_logo_position: false,
		email_btn_bkgd_color: false,
		email_btn_text_color: false,
		allow_edit_document_after_signing: false,
		allow_embedded_extended_token_expiration: false,
		email_footer_enabled: false,
		every_signature_and_initials_field_requires_user_authentication: false,
		enable_render_pages_in_editor_as_images: false,
		enable_team_admin_move_docs: false,
		disable_recipients_list_from_editor: false,
		allow_team_admin_rename_docs: false,
		disable_email_recipients: false,
		parse_only_signature_fields: false,
		flatten_before_aspose: false,
		run_experiments: false,
		disable_form_search: false,
		allow_team_admin_create_csv_report_for_shared_template: false,
		enable_team_generic_email: false,
		use_team_generic_data: false,
		signing_reason: false,
		allow_qes: false,
		enable_qes: false,
		advanced_signing_flow: false,
	},
	is_favorite: false,
	entity_type: 'document',
	origin_document_id: null,
	recently_used: '1699976268',
});
